name = "router"
type = "webpack"

account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-06-27"

kv_namespaces = [
  { binding = "okta_auth0_saml_sp_mappings", id = "c0d2f5de8f604cd0b853e54bd0146421" }
]
